version: '3.8'

services:
  postgres:
    build: PostgresInit
    environment:
      POSTGRES_DB: AlertSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2105
    volumes:
      - /home/nikita/JavaProject/PostgresDockerData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend-alert-api:
    build:
      context: ./backendSiteDiplom
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/AlertSystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2105      

