-- Создаем таблицу People
CREATE TABLE People(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT,
    password TEXT,
    email TEXT,
    Nname TEXT,
    serName TEXT,
	role Text
);

-- Создаем таблицу Project
CREATE TABLE Course(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT,
    description TEXT,
	creator int
);

-- Создаем таблицу PeopleInProject
CREATE TABLE PeopleInCourse(
    idCourse INT REFERENCES Course(id),
    idPeople INT REFERENCES People(id),
	infoToRep TEXT,
    PRIMARY KEY(idCourse, idPeople)
);

CREATE TABLE Task(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idCourse INT REFERENCES Course(id),
	label TEXT,
	description TEXT
);
